# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gopay_id', models.BigIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('refresh_counter', models.IntegerField(default=0)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('_status', models.TextField()),
                ('_command', models.TextField()),
            ],
        ),
    ]
