# Generated by Django 4.0.3 on 2022-03-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gopay_django_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created'], 'verbose_name': 'Platba GoPay', 'verbose_name_plural': 'Platby GoPay'},
        ),
    ]
